spring.application.name=scooter-service
jwt.secret= "my-super-secret-key-my-super-secret-key-my-super-secret-key"
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/scooter_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

